// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD5WIxan4QtaO31CCq6B4v68ACM8QBTTY',
    appId: '1:846434681297:web:c502e652f1427e6085a0f0',
    messagingSenderId: '846434681297',
    projectId: 'fir-5-64891',
    authDomain: 'fir-5-64891.firebaseapp.com',
    storageBucket: 'fir-5-64891.appspot.com',
    measurementId: 'G-REWRBZ0S2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBxgQe7kBuzb0-keaoydWWiAPC-QbfrE0',
    appId: '1:846434681297:android:85f0d6e30585086e85a0f0',
    messagingSenderId: '846434681297',
    projectId: 'fir-5-64891',
    storageBucket: 'fir-5-64891.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPE1KmtKwGMrpBDpgkHw37nUxFuxqTxPE',
    appId: '1:846434681297:ios:1dac05a8e7e1a21385a0f0',
    messagingSenderId: '846434681297',
    projectId: 'fir-5-64891',
    storageBucket: 'fir-5-64891.appspot.com',
    iosBundleId: 'com.example.firebase5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPE1KmtKwGMrpBDpgkHw37nUxFuxqTxPE',
    appId: '1:846434681297:ios:1dac05a8e7e1a21385a0f0',
    messagingSenderId: '846434681297',
    projectId: 'fir-5-64891',
    storageBucket: 'fir-5-64891.appspot.com',
    iosBundleId: 'com.example.firebase5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDD5WIxan4QtaO31CCq6B4v68ACM8QBTTY',
    appId: '1:846434681297:web:6f4ceede1d3f8dfc85a0f0',
    messagingSenderId: '846434681297',
    projectId: 'fir-5-64891',
    authDomain: 'fir-5-64891.firebaseapp.com',
    storageBucket: 'fir-5-64891.appspot.com',
    measurementId: 'G-183YW89VYD',
  );
}
